#!/bin/sh
: ' Makeall  --  Print message about making all of Xinu'
:
: 'Makeall'
:
PATH=/bin:/usr/bin
echo
echo '*** Making {Xinu--directory}/src/sys/con'
cd con
make
make install
cd ..
echo '*** Making {Xinu--directory}/src/sys/sys'
cd sys
make
make install
