#!/bin/sh
: 'Makeall  --  make all of src/cmd for VAX Xinu'
:
PATH=/bin:/usr/bin
echo
echo '*** Making commands in {Xinu-directory}/src/cmd'
make
make install
for i in *
do if test -d $i
   then cd $i
	echo
        echo "*** Making commands in {Xinu-directory}/src/cmd/$i"
	make
        make install
        cd ..
    fi
done
