struct line
		*ActuallySearch(),
		*AllocLine(),
		*CopyLine(),
		*CopyLines(),
		*DeleteLine(),
		*DeleteChar(),
		*EnterInsertMode(),
		*FindBotLine(),
		*FindTopLine(),
		*FreeLines(),
		*GetLastLine(),
		*GotoTopOfFile(),
		*GotoEndOfFile(),
		*GotoLine(),
		*LoadFile(),
 		*MeldLines(),
	 	*MoveCharLeft(),
		*MoveCharRight(),
		*MoveCharUp(),
		*MoveCharDown(),
		*MoveWordLeft(),
		*MoveWordRight(),
		*PutAfter(),
		*ReadInputFile(),
		*ScrollDn(),
		*ScrollUp(),
		*Search(),
		*UndoLastDeletion();

char 		*scwgetstr(),
     		*substr();
