#
#  Make man2 ConcurrenC Manual Pages
#


MACROS	=	../tmac.an

FILES	=	$(MACROS)	\
		intro.2ccc	\
		chprio.2ccc close.2ccc control.2ccc create.2ccc \
		freemem.2ccc \
		getc.2ccc getmem.2ccc getpid.2ccc getprio.2ccc gettid.2ccc \
		kill.2ccc \
		mark.2ccc \
		open.2ccc \
		panic.2ccc pcount.2ccc pcreate.2ccc pdelete.2ccc \
		preceive.2ccc preset.2ccc psend.2ccc putc.2ccc \
		read.2ccc receive.2ccc resume.2ccc \
		scount.2ccc screate.2ccc sdelete.2ccc seek.2ccc send.2ccc \
		signal.2ccc sleep.2ccc sreset.2ccc ssignal.2ccc \
		suspend.2ccc swait.2ccc \
		tkill.2ccc treceive.2ccc tsend.2ccc tstart.2ccc \
		wait.2ccc write.2ccc \
		Oadvise.2 Ovfork.2 \
		execve.2 \
		fcntl.2 flock.2 fork.2 \
		getdtablesize.2 getitimer.2 \
		kill.2 killpg.2 \
		profil.2 ptrace.2 \
		select.2 sigblock.2 sigpause.2 sigsetmask.2 sigvec.2 syscall.2 \
		vhangup.2 \
		wait.2

all:		$(FILES)

chprio.2ccc :	raw/chprio.2ccc.raw
		nroff ../tmac.an raw/chprio.2ccc.raw > chprio.2ccc
  
close.2ccc :	raw/close.2ccc.raw
		nroff ../tmac.an raw/close.2ccc.raw > close.2ccc
  
control.2ccc :	raw/control.2ccc.raw
		nroff ../tmac.an raw/control.2ccc.raw > control.2ccc
  
create.2ccc :	raw/create.2ccc.raw
		nroff ../tmac.an raw/create.2ccc.raw > create.2ccc
  
freemem.2ccc :	raw/freemem.2ccc.raw
		nroff ../tmac.an raw/freemem.2ccc.raw > freemem.2ccc
  
getc.2ccc :	raw/getc.2ccc.raw
		nroff ../tmac.an raw/getc.2ccc.raw > getc.2ccc
  
getmem.2ccc :	raw/getmem.2ccc.raw
		nroff ../tmac.an raw/getmem.2ccc.raw > getmem.2ccc
  
getpid.2ccc :	raw/getpid.2ccc.raw
		nroff ../tmac.an raw/getpid.2ccc.raw > getpid.2ccc
  
getprio.2ccc :	raw/getprio.2ccc.raw
		nroff ../tmac.an raw/getprio.2ccc.raw > getprio.2ccc
  
gettid.2ccc :	raw/gettid.2ccc.raw
		nroff ../tmac.an raw/gettid.2ccc.raw > gettid.2ccc
  
intro.2ccc :	raw/intro.2ccc.raw
		nroff ../tmac.an raw/intro.2ccc.raw > intro.2ccc
  
kill.2ccc :	raw/kill.2ccc.raw
		nroff ../tmac.an raw/kill.2ccc.raw > kill.2ccc
  
mark.2ccc :	raw/mark.2ccc.raw
		nroff ../tmac.an raw/mark.2ccc.raw > mark.2ccc
  
open.2ccc :	raw/open.2ccc.raw
		nroff ../tmac.an raw/open.2ccc.raw > open.2ccc
  
panic.2ccc :	raw/panic.2ccc.raw
		nroff ../tmac.an raw/panic.2ccc.raw > panic.2ccc
  
pcount.2ccc :	raw/pcount.2ccc.raw
		nroff ../tmac.an raw/pcount.2ccc.raw > pcount.2ccc
  
pcreate.2ccc :	raw/pcreate.2ccc.raw
		nroff ../tmac.an raw/pcreate.2ccc.raw > pcreate.2ccc
  
pdelete.2ccc :	raw/pdelete.2ccc.raw
		nroff ../tmac.an raw/pdelete.2ccc.raw > pdelete.2ccc
  
preceive.2ccc :	raw/preceive.2ccc.raw
		nroff ../tmac.an raw/preceive.2ccc.raw > preceive.2ccc
  
preset.2ccc :	raw/preset.2ccc.raw
		nroff ../tmac.an raw/preset.2ccc.raw > preset.2ccc
  
psend.2ccc :	raw/psend.2ccc.raw
		nroff ../tmac.an raw/psend.2ccc.raw > psend.2ccc
  
putc.2ccc :	raw/putc.2ccc.raw
		nroff ../tmac.an raw/putc.2ccc.raw > putc.2ccc
  
read.2ccc :	raw/read.2ccc.raw
		nroff ../tmac.an raw/read.2ccc.raw > read.2ccc
  
receive.2ccc :	raw/receive.2ccc.raw
		nroff ../tmac.an raw/receive.2ccc.raw > receive.2ccc
  
resume.2ccc :	raw/resume.2ccc.raw
		nroff ../tmac.an raw/resume.2ccc.raw > resume.2ccc
  
scount.2ccc :	raw/scount.2ccc.raw
		nroff ../tmac.an raw/scount.2ccc.raw > scount.2ccc
  
screate.2ccc :	raw/screate.2ccc.raw
		nroff ../tmac.an raw/screate.2ccc.raw > screate.2ccc
  
sdelete.2ccc :	raw/sdelete.2ccc.raw
		nroff ../tmac.an raw/sdelete.2ccc.raw > sdelete.2ccc
  
seek.2ccc :	raw/seek.2ccc.raw
		nroff ../tmac.an raw/seek.2ccc.raw > seek.2ccc
  
send.2ccc :	raw/send.2ccc.raw
		nroff ../tmac.an raw/send.2ccc.raw > send.2ccc
  
signal.2ccc :	raw/signal.2ccc.raw
		nroff ../tmac.an raw/signal.2ccc.raw > signal.2ccc
  
sleep.2ccc :	raw/sleep.2ccc.raw
		nroff ../tmac.an raw/sleep.2ccc.raw > sleep.2ccc
  
sreset.2ccc :	raw/sreset.2ccc.raw
		nroff ../tmac.an raw/sreset.2ccc.raw > sreset.2ccc
  
ssignal.2ccc :	raw/ssignal.2ccc.raw
		nroff ../tmac.an raw/ssignal.2ccc.raw > ssignal.2ccc
  
suspend.2ccc :	raw/suspend.2ccc.raw
		nroff ../tmac.an raw/suspend.2ccc.raw > suspend.2ccc
  
swait.2ccc :	raw/swait.2ccc.raw
		nroff ../tmac.an raw/swait.2ccc.raw > swait.2ccc
  
tkill.2ccc :	raw/tkill.2ccc.raw
		nroff ../tmac.an raw/tkill.2ccc.raw > tkill.2ccc
  
treceive.2ccc :	raw/treceive.2ccc.raw
		nroff ../tmac.an raw/treceive.2ccc.raw > treceive.2ccc
  
tsend.2ccc :	raw/tsend.2ccc.raw
		nroff ../tmac.an raw/tsend.2ccc.raw > tsend.2ccc
  
tstart.2ccc :	raw/tstart.2ccc.raw
		nroff ../tmac.an raw/tstart.2ccc.raw > tstart.2ccc
  
wait.2ccc :	raw/wait.2ccc.raw
		nroff ../tmac.an raw/wait.2ccc.raw > wait.2ccc
  
write.2ccc :	raw/write.2ccc.raw
		nroff ../tmac.an raw/write.2ccc.raw > write.2ccc
  
Oadvise.2 :	raw/Oadvise.2.raw
		nroff ../tmac.an raw/Oadvise.2.raw > Oadvise.2
  
Ovfork.2 :	raw/Ovfork.2.raw
		nroff ../tmac.an raw/Ovfork.2.raw > Ovfork.2
  
execve.2 :	raw/execve.2.raw
		nroff ../tmac.an raw/execve.2.raw > execve.2
  
fcntl.2 :	raw/fcntl.2.raw
		nroff ../tmac.an raw/fcntl.2.raw > fcntl.2
  
flock.2 :	raw/flock.2.raw
		nroff ../tmac.an raw/flock.2.raw > flock.2
  
fork.2 :	raw/fork.2.raw
		nroff ../tmac.an raw/fork.2.raw > fork.2
  
getdtablesize.2 :	raw/getdtablesize.2.raw
		nroff ../tmac.an raw/getdtablesize.2.raw > getdtablesize.2
  
getitimer.2 :	raw/getitimer.2.raw
		nroff ../tmac.an raw/getitimer.2.raw > getitimer.2
  
kill.2 :	raw/kill.2.raw
		nroff ../tmac.an raw/kill.2.raw > kill.2
  
killpg.2 :	raw/killpg.2.raw
		nroff ../tmac.an raw/killpg.2.raw > killpg.2
  
profil.2 :	raw/profil.2.raw
		nroff ../tmac.an raw/profil.2.raw > profil.2
  
ptrace.2 :	raw/ptrace.2.raw
		nroff ../tmac.an raw/ptrace.2.raw > ptrace.2
  
select.2 :	raw/select.2.raw
		nroff ../tmac.an raw/select.2.raw > select.2
  
sigblock.2 :	raw/sigblock.2.raw
		nroff ../tmac.an raw/sigblock.2.raw > sigblock.2
  
sigpause.2 :	raw/sigpause.2.raw
		nroff ../tmac.an raw/sigpause.2.raw > sigpause.2
  
sigsetmask.2 :	raw/sigsetmask.2.raw
		nroff ../tmac.an raw/sigsetmask.2.raw > sigsetmask.2
  
sigvec.2 :	raw/sigvec.2.raw
		nroff ../tmac.an raw/sigvec.2.raw > sigvec.2
  
syscall.2 :	raw/syscall.2.raw
		nroff ../tmac.an raw/syscall.2.raw > syscall.2
  
vhangup.2 :	raw/vhangup.2.raw
		nroff ../tmac.an raw/vhangup.2.raw > vhangup.2
  
wait.2 :	raw/wait.2.raw
		nroff ../tmac.an raw/wait.2.raw > wait.2

install:
		@echo no installation possible - use "'make print'"

clean:
		rm -rf *.2ccc *.2

print:		listings

listings:	$(FILES)
		cat *.2ccc *.2 | sed '1,2d;s/^/	/' | lpr
